# Generated by Django 3.1.2 on 2021-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoddockapp', '0007_auto_20210105_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
