# Generated by Django 3.1.2 on 2021-01-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoddockapp', '0009_regularadrress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularAdrress',
            new_name='RegularAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='regular_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoddockapp.regularaddress'),
        ),
    ]
