# Generated by Django 3.1.3 on 2021-01-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoddockapp', '0002_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
