# Generated by Django 3.1.3 on 2021-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoddockapp', '0003_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
